version: '3.1'

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'bestuser'
      MYSQL_PASSWORD: 'bestuser'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci